// Copy the engine's browser client into this repository.
//
// The plugin used to import it across a sibling checkout, which meant this
// repository could not be built by anyone who did not also have the engine —
// not by a reviewer, not by CI, not by the community directory's build check.
// A vendored copy is the price of being buildable alone.
//
//   node scripts/vendor-client.mjs           refresh the copy
//   node scripts/vendor-client.mjs --check   fail if it has drifted
//
// The copy is generated, never edited. `--check` is what keeps that true: it
// runs wherever the engine is present, and it is the answer to the objection
// that a copy per product drifts silently. Here there is one copy, and a
// command that says when it is stale.
import { createHash } from "node:crypto";
import {
  cpSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const REPO = join(dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE = join(REPO, "../opensync/packages/client/src");
const VENDOR = join(REPO, "vendor/opensync-client");
const STAMP = join(VENDOR, "VENDORED.json");

// What the plugin actually reaches for. `ui/` is the web apps' shared
// components and `opensync_wasm_bg.wasm` is the loose binary the glue falls
// back to — neither is reachable from this plugin, and the bytes are already
// in `inline.ts` as base64. `opensync_wasm_bg.wasm.d.ts` describes that binary's
// raw exports and nothing imports it, so it is left behind too.
const FILES = [
  "index.ts",
  "hosted.ts",
  "relay.ts",
  "session.ts",
  "pairing.ts",
  "qr.ts",
  "scan.ts",
  "wasm/inline.ts",
  "wasm/opensync_wasm.js",
  "wasm/opensync_wasm.d.ts",
];

/**
 * What a vendored file should contain, given the engine's copy of it.
 *
 * wasm-bindgen opens every file it generates with a blanket
 * `/* eslint-disable *\/` (and a `tslint` twin). The community directory's
 * scan treats an unlimited disable as an error — rightly, since it would
 * silence its security rules over the whole file — and failed 0.1.1 on it.
 * The comment is boilerplate, not a considered exemption: removing it changes
 * no behaviour and lets the file be read by the same rules as everything else.
 *
 * The check applies this too, so a stripped copy still matches its source.
 */
function vendored(path) {
  const text = readFileSync(path, "utf8");
  if (!/\.(d\.ts|js)$/.test(path)) return text;
  return text.replace(/^\/\* (?:tslint:|eslint-)disable \*\/\r?\n/gm, "");
}

const sha = (text) => createHash("sha256").update(text).digest("hex").slice(0, 16);
const check = process.argv.includes("--check");

if (!existsSync(SOURCE)) {
  // Not an error. Most clones of this repository will never have the engine
  // beside them, and they do not need it — that is the point of vendoring.
  console.log(`no engine at ${relative(REPO, SOURCE)} — nothing to ${check ? "check" : "refresh"}`);
  process.exit(0);
}

if (check) {
  const stamp = existsSync(STAMP) ? JSON.parse(readFileSync(STAMP, "utf8")) : { files: {} };
  const drifted = [];
  for (const f of FILES) {
    const from = join(SOURCE, f);
    const mine = join(VENDOR, f);
    if (!existsSync(mine)) {
      drifted.push(`${f} — missing from the copy`);
      continue;
    }
    if (sha(vendored(from)) !== sha(readFileSync(mine, "utf8"))) drifted.push(`${f} — differs from the engine`);
  }
  const extra = Object.keys(stamp.files ?? {}).filter((f) => !FILES.includes(f));
  for (const f of extra) drifted.push(`${f} — vendored but no longer wanted`);

  if (drifted.length > 0) {
    console.error("the vendored client has drifted from the engine:\n");
    for (const d of drifted) console.error(`  ${d}`);
    console.error("\nrun `npm run vendor` and commit the result.");
    process.exit(1);
  }
  console.log(`vendored client matches the engine (${FILES.length} files)`);
  process.exit(0);
}

rmSync(VENDOR, { recursive: true, force: true });
mkdirSync(join(VENDOR, "wasm"), { recursive: true });

const files = {};
let bytes = 0;
for (const f of FILES) {
  const from = join(SOURCE, f);
  if (!existsSync(from)) {
    console.error(`the engine has no ${f} — has the client been rearranged?`);
    process.exit(1);
  }
  const text = vendored(from);
  writeFileSync(join(VENDOR, f), text);
  files[f] = sha(text);
  bytes += Buffer.byteLength(text);
}

writeFileSync(
  STAMP,
  `${JSON.stringify(
    {
      note: "Generated by scripts/vendor-client.mjs. Do not edit anything in this directory.",
      source: "github.com/open-sync/opensync — packages/client/src",
      vendored: new Date().toISOString().slice(0, 10),
      files,
    },
    null,
    2,
  )}\n`,
);

writeFileSync(
  join(VENDOR, "README.md"),
  `# Vendored: the OpenSync browser client

**Generated. Do not edit anything in this directory.**

These files are copied verbatim from the engine's \`packages/client/src\` by
\`scripts/vendor-client.mjs\`. They are here so that this repository builds on
its own — a reviewer, a CI runner or the community directory's build check
clones one repository and runs \`npm run build\`, and none of them has the
engine beside them.

\`wasm/inline.ts\` is the compiled Rust core as base64. Its source is the
\`opensync-*\` crates in the engine repository; it is not written by hand and
cannot be read usefully here.

To refresh, with the engine checked out beside this repository:

    npm run vendor        # copy again
    npm run vendor:check  # fail if the copy has drifted

\`vendor:check\` runs in the test suite. Where the engine is absent it passes
quietly, because most clones will never have it.
`,
);

const listed = readdirSync(VENDOR, { recursive: true }).filter((f) => !statSync(join(VENDOR, f)).isDirectory());
console.log(`vendored ${FILES.length} files, ${(bytes / 1024 / 1024).toFixed(2)} MB → vendor/opensync-client`);
console.log(`  ${listed.join("\n  ")}`);
